services:
  - type: web
    name: ulcer-prediction
    env: python
    plan: free
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py


